engines/orders/config/routes.rb
Dwl::Core::Engine.routes.draw do
  scope module: 'orders' do
    resources :orders, only: [:index, :new, :create]
    get 'orders/metrics' =>  'metrics#index'
  end
end

engines/orders/app/models/dwl/application_record.rb
module Dwl
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

engines/orders/app/models/dwl/orders/order.rb
module Dwl::Orders
  class Order < ActiveRecord::Base
    belongs_to :position
    belongs_to :item
    belongs_to :user

    enum status: %w{created assigned delivered pickedup cancelled}
  end
end

engines/orders/app/controllers/dwl/orders/application_controller.rb
module Dwl
  module Orders
    class ApplicationController < Dwl::ActionController::Base
    end
  end
end

engines/orders/app/controllers/dwl/orders/metrics_controller.rb
require_dependency "dwl/application_controller"

module Dwl
  module Orders
    class MetricsController < ApplicationController

      # GET /orders/metrics
      def index

      end
    end
  end
end

engines/orders/app/controllers/dwl/orders/orders_controller.rb
require_dependency "dwl/application_controller"

module Dwl
  module Orders
    class OrdersController < ApplicationController
      before_action :set_order, only: [:show, :edit, :update, :destroy]

      # GET /orders
      def index
        @orders = Order.all
      end

      # GET /orders/new
      def new
        @order = current_user.orders.build
      end

      # POST /orders
      def create
        @order = current_user.orders.build(order_params)
        if @order.save
          # nothing
        end
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_order
          @order = Order.find(params[:id])
        end

        # Only allow a trusted parameter "white list" through.
        def order_params
          params.require(:order).permit(:customer_name, :customer_phone, :giveaway_selection,
                                        :deliver_order_number, :scan_badge_info,
                                        :order_compartment, :delivery_method, :status,
                                        :assigned_date, :delivered_date,
                                        :pickup_email_sent_date, :pickup_date, :position_id,
                                        :item_id)
        end
    end

  end
end

engines/orders/app/helpers/dwl/orders/application_helper.rb
module Dwl
  module Orders
    module ApplicationHelper
    end
  end
end

engines/orders/app/views/dwl/orders/metrics/index.html.erb
<h1 class="pull-left">Metrics</h1>
<%= render 'shared/nav'%>

engines/orders/app/views/dwl/orders/orders/_form.html.erb
<div id="order-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title"><%= title %></h4>
      </div>
      <%=  form_for([dwl, @order], remote: true) do  |f| %>
        <div class="modal-body">
          <div class="alert alert-danger" role="alert" style="display: none;"></div>
            <div class="form-group">
              <%= f.label :status, class: "control-label" %>
              <%= f.select :status, Dwl::Orders::Order.statuses.keys, class: "form-control"%>
            </div>
            <div class="form-group">
              <div>
                <%= f.submit "Create Order", class: "btn btn-primary" %>
              </div>
            </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      <% end %>
    </div><!-- end /.modal-content -->
  </div><!-- end /.modal-dialog -->
</div><!-- end /.modal -->

engines/orders/app/views/dwl/orders/orders/_row.html.erb
<tr id="<%= order.id %>">
  <td><%= order.id %></td>
</tr>

engines/orders/app/views/dwl/orders/orders/create.js.erb
<% if @order.errors.empty? %>
  $('table tbody').append('<%= j render "row", order: @order %>');
  $('.alert').html("Order was successfully created.").show();
  $('#order-modal').modal('hide');
<% else %>
  // show first error
  alert('<%= @order.errors.full_messages[0] %>');
<% end %>

engines/orders/app/views/dwl/orders/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

engines/orders/app/views/dwl/orders/orders/index.html.erb
<h2 class="pull-left">Listing Orders</h2>
<%= render 'shared/nav' %>
<hr>
<div class="row">
  <div class="col-lg-9">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Orders Awaiting Delivery
      </div>

      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Phone</th>
            </tr>
          </thead>
          <tbody>
            <% @orders.each do |order| %>
              <%= render "row", order: order %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div><!-- end div table -->
  </div><!-- end col-lg-9 -->
  <div class="col-lg-3 col-md-12">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Orders Queued for a compartment:
      </div>

      <div class="table-responsive">
        <table class="table">
          <tbody>
            <% @orders.each do |order| %>
              <tr>
                <td><%= order.id %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div><!-- end table responsive -->
    </div>

  </div><!-- end col-lg-3 -->
</div><!-- end row -->

engines/orders/app/views/dwl/orders/orders/new.js.erb
$('<%= j render "form", title: "New Order" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

engines/orders/app/views/dwl/orders/overrides/_orders_link.html.erb
<li class="<%= active(dwl.orders_path) %>">
  <%= link_to 'Orders', dwl.orders_path %>
</li>

engines/orders/app/views/dwl/orders/overrides/_welcome.html.erb
<div class="col-md-6 box-enter">
  <ul class="bs-glyphicon-list">
    <li>
      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
      <span class="glyphicon-class">Enter an Order</span>
    </li>
  </ul>
</div>
<div class="col-md-6 box-enter">
  <ul class="bs-glyphicon-list">
    <li>
      <span class="glyphicon glyphicon-screenshot" aria-hidden="true"></span>
      <span class="glyphicon-class">Pick up an Order</span>
    </li>
  </ul>
</div>

engines/orders/app/views/dwl/orders/overrides/_welcome_orders.html.erb
<div class="col-md-6 box-enter">
  <%= link_to dwl.new_order_path, remote: true do %>
    <ul class="bs-glyphicon-list">
      <li>
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        <span class="glyphicon-class">Enter an Order</span>
      </li>
    </ul>
  <% end %>
</div>
<div class="col-md-6 box-enter">
  <%= link_to '#', remote: true do %>
    <ul class="bs-glyphicon-list">
      <li>
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        <span class="glyphicon-class">Pickup an Order</span>
      </li>
    </ul>
  <% end %>
</div>

engines/orders/app/views/dwl/orders/shared/_nav.html.erb
<ul class="nav nav-pills navbar-right">
  <li role="presentation" class="<%= active(dwl.orders_path) %>">
    <%= link_to 'Orders', dwl.orders_path %>
  </li>

  <li role="presentation" class="<%= active(dwl.orders_metrics_path) %>">
    <%= link_to 'Metrics', dwl.orders_metrics_path %>
  </li>
</ul>

<div class="clearfix"></div>